"""empty message

Revision ID: befd49b8b360
Revises: 
Create Date: 2021-09-30 23:26:34.349627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'befd49b8b360'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mspin', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mspin', sa.Integer(), nullable=False),
    sa.Column('registered_img_id', sa.Integer(), nullable=False),
    sa.Column('verified_path', sa.String(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registered_img_id'], ['registered_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('registered_images')
    # ### end Alembic commands ###
